Week 1
LeoKuD/tic-tac-toe pull request #1
Opened 2022-02-08 14:59 UTC by LeoKuD

Done: 
- play with computer;
- play with friend;
- win counter;
- history navigation;
- reset;
- save to localStorage;

2022-02-14 19:49 UTC, maximsan requested changes
Hello! I left some comment! Please review and fix ASAP. Thanks! UI looks dark and it's  🆒

2022-02-14 19:49 UTC, maximsan commented on src/components/boadr/index.jsx
> +          {renderSquare(8)}
you can just use array.map(...) to generate all items almost in one row of code

2022-02-14 19:49 UTC, maximsan commented on src/components/navigation/index.jsx
> +        disabled={stepNumber ? false : true}
you can do like this `disabled={!!stepNumber}`

2022-02-14 19:49 UTC, maximsan commented on src/components/navigation/index.jsx
> +        disabled={stepNumber + 1 < history.length ? false : true}
don't repeat `stepNumber + 1 < history.length` twice

2022-02-14 19:49 UTC, maximsan commented on src/constants.js
> +export const TICTACTOEKEYS = {
why so strange? use simpler name and add space `GAME_KEYS`

2022-02-14 19:49 UTC, maximsan commented on src/constants.js
> +export const PLAYERSKEYS = {
why so strange?  add space `PLAYERS_KEYS`

2022-02-14 19:49 UTC, maximsan commented on src/helpers.js
> +      index = random;
why do you need this extra line ? create helper method, you repeat the same calculations for different combinations

2022-02-14 19:49 UTC, maximsan commented on src/index.css
> +  color: #fff;
if you repeat the same value more then once in several places please consider using :root selector with variables;

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    };
here you can also call the method I mentioned below

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    };
here you can also call the method to init a state I mentioned below

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    if (prevState !== this.state) {
I'm pretty sure that they different all the time, because they are objects 😄

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +      this.setState({
use callback version of setState to update state with previous state

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    this.setState({ isStart: !this.state.isStart });
we don't call this.state in this.setState. it's `anti-pattern`. you should use callback version of setState to update state with previous state

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    this.isLevelHard = !this.isLevelHard;
it should not affect you UI, you should toggle it only inside `this.setState` by using callback version of `setState`

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +      isComputerMode: !this.state.isComputerMode,
you shouldn't relay on this.state, you should update state by using callback version of `setState`

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    const current = history[this.state.stepNumber].squares;
you shouldn't relay on this.state, you should update state by using `setState`

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    const current = history[this.state.stepNumber].squares;
you shouldn't relay on this.state, you should update state by using `setState`

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    const board = document.querySelector('.game-board');
create object with keys for all your selectors

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    board.classList.toggle('blocked');
create object with keys for all your specific classes

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +      isNavigationMode: false,
again use the init state method

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +      isNavigationMode: true,
you shouldn't relay on this.state, you should update state by using callback version of `setState`

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    let currentMove = this.state.stepNumber;
do destructuring assignment here

2022-02-14 19:49 UTC, maximsan commented on src/index.js
> +    }
create a method for this outside render

2022-02-15 06:55 UTC, LeoKuD commented on src/components/boadr/index.jsx
> +          {renderSquare(8)}
```suggestion
          export function Board({ onClick, squares }) {
  return (
    <div className={style.board}>
      {squares.map((item, index) => {
        function clickHandler() {
          onClick(index);
        }
        return <Square key={index} value={item} onClick={clickHandler} />;
      })}
    </div>
  );
}

```

2022-02-15 07:02 UTC, LeoKuD commented on src/components/navigation/index.jsx
> +        disabled={stepNumber ? false : true}
```suggestion
                disabled={!stepNumber}
```

2022-02-15 07:11 UTC, LeoKuD commented on src/components/navigation/index.jsx
> +        disabled={stepNumber + 1 < history.length ? false : true}
```suggestion
        className={isNextStep ? '' : style.disabled}
        disabled={!isNextStep}
```

2022-02-15 07:14 UTC, LeoKuD commented on src/constants.js
> +export const TICTACTOEKEYS = {
```suggestion
export const GAME_KEYS = {
```

2022-02-15 07:15 UTC, LeoKuD commented on src/constants.js
> +export const PLAYERSKEYS = {
```suggestion
export const PLAYERS_KEYS = {
```

2022-02-15 07:17 UTC, LeoKuD commented on src/helpers.js
> +      index = random;
```suggestion
          index = randomX[Math.floor(Math.random() * randomX.length)];
```

2022-02-15 07:37 UTC, LeoKuD commented on src/helpers.js
> +      index = random;
```suggestion
      return getRandomIndex(computerWinnerСombinations, currentGameState)
```

2022-02-15 07:38 UTC, LeoKuD commented on src/helpers.js
> +      index = random;
function getRandomIndex(combinations, currentGameState) {
    let randomLine = combinations[
      Math.floor(Math.random() * combinations.length)
    ].filter((item) => !currentGameState[item]);

    return randomLine[Math.floor(Math.random() * randomLine.length)];
  }

2022-02-15 07:54 UTC, LeoKuD commented on src/helpers.js
> +      emptySquares[Math.floor(Math.random() * emptySquares.length)];
```suggestion
      return calculateRandomIndex(emptySquares);
```

2022-02-15 08:15 UTC, LeoKuD commented on src/index.css
> +  color: #fff;
Fixed. Created :root selector in the root css file and used it in other files.

```
:root {
  --bg-color-primary: #000;
  --color-primary: #fff;
}
```

2022-02-15 09:23 UTC, LeoKuD commented on src/index.js
> +        playerOne: true,
```
  initialState() {
    this.score = JSON.parse(localStorage.getItem('score')) || {
      x: 0,
      o: 0,
      tie: 0,
      roundCompleted: false,
    };
    this.isLevelHard = true;
    
    return JSON.parse(localStorage.getItem('state')) || { 
      history: [
        {
          squares: Array(9).fill(null),
        },
      ],
      nextPlayer: true,
      stepNumber: 0,
      isComputerMode: false,
      isNavigationMode: false,
      isStart: false,
      playerOne: true,
    };
  }
```

`    this.state = this.initialState();`

2022-02-15 09:24 UTC, LeoKuD commented on src/index.js
> +        playerOne: true,
And deleted componentDidMount()

2022-02-15 09:25 UTC, LeoKuD commented on src/index.js
> +      tie: 0,
corrected above

2022-02-15 09:25 UTC, LeoKuD commented on src/index.js
> +    };
corrected above

2022-02-15 09:25 UTC, LeoKuD commented on src/index.js
> +    };
corrected above

2022-02-15 10:02 UTC, LeoKuD commented on src/index.js
> +    if (prevState !== this.state) {
Yes, deleted this if.

2022-02-15 10:03 UTC, LeoKuD commented on src/index.js
> +    if (prevState !== this.state) {
```suggestion
        localStorage.setItem('state', JSON.stringify(this.state));
```

2022-02-15 12:00 UTC, LeoKuD commented on src/index.js
> +      this.setState({
```suggestion
           this.setState((state) => {
        if (state.isStart) {
          squares[i] = this.state.nextPlayer ? GAME_KEYS.x : GAME_KEYS.o;
          return {
            history: history.concat([
              {
                squares: squares,
              },
            ]),
            stepNumber: history.length,
            nextPlayer: !state.nextPlayer,
            isNavigationMode: false,
          };
        }
      });
```

2022-02-15 12:01 UTC, LeoKuD commented on src/index.js
> +    this.setState({ isStart: !this.state.isStart });
```
    this.setState((state) => {
      if (!state.isStart) {
        this.resetGame();
      }
      return { isStart: !state.isStart };
    });
```

2022-02-15 12:05 UTC, LeoKuD commented on src/index.js
> +    this.isLevelHard = !this.isLevelHard;
```suggestion
      changeLavel() {
    this.setState((state) => {
      return { isLevelHard: !state.isLevelHard };
    });
  }
```

2022-02-15 12:22 UTC, LeoKuD commented on src/index.js
> +      isComputerMode: !this.state.isComputerMode,
```suggestion
        changeMode() {
    this.setState((state) => {
      return {
        isComputerMode: !state.isComputerMode,
      }
    });
```

2022-02-15 12:28 UTC, LeoKuD commented on src/index.js
> +    const current = history[this.state.stepNumber].squares;
```suggestion
      getRandomEasy() {
    let current = null;
    this.setState((state) => {
      current = state.history[state.stepNumber].squares;
    })
    return getIndexEasyLevel(current);
  }
```

2022-02-15 12:32 UTC, LeoKuD commented on src/index.js
> +    const current = history[this.state.stepNumber].squares;
```suggestion
      getRandomHard() {
    let current = null;
    let stepNumber = null;
    this.setState((state) => {
      stepNumber = state.stepNumber;
      current = state.history[state.stepNumber].squares;
    })

    return getIndexHardLevel(current, stepNumber);
  }
```

2022-02-15 12:40 UTC, LeoKuD commented on src/index.js
> +    const board = document.querySelector('.game-board');
```
  export const SELECTOR_KEYS = {
    game: 'game',
    status: 'status',
    gameBoard: 'game-board',
    blocked: 'blocked'
  }
```

2022-02-15 12:45 UTC, LeoKuD commented on src/index.js
> +    const board = document.querySelector('.game-board');
```
export const SELECTORS_KEYS = {
    game: 'game',
    status: 'status',
    gameBoard: 'game-board',
    blocked: 'blocked'
  }
```

2022-02-15 12:46 UTC, LeoKuD commented on src/index.js
> +    board.classList.toggle('blocked');
corrected above

2022-02-15 12:52 UTC, LeoKuD commented on src/index.js
> +      isNavigationMode: false,
I can't use it here because method initialState rewrite all state

2022-02-15 13:03 UTC, LeoKuD commented on src/index.js
> +      isNavigationMode: true,
```suggestion
        jumpTo(direction) {
    this.setState((state) => {
      let currentMove = state.stepNumber;
      return {
        stepNumber: direction === NAVIGATION_KEYS.back ? --currentMove : ++currentMove,
        nextPlayer: state.playerOne
          ? currentMove % 2 === 0
          : !currentMove % 2 === 0,
        isNavigationMode: true,
      };
    });
  }
```

2022-02-15 13:14 UTC, LeoKuD commented on src/index.js
> +    let currentMove = this.state.stepNumber;
```suggestion
      let {stepNumber} = state;
```

2022-02-15 13:42 UTC, LeoKuD commented on src/index.js
> +    }
```
  updateStatus() {
    const history = this.state.history;
    const current = history[this.state.stepNumber];
    const winner = calculateWinner(current.squares);
    let status;

    if (winner && !this.score.roundCompleted) {
      status = `Winner: ${winner}`;
      this.updateScore(winner);
    } else {
      status = `Next player: ${
        this.state.nextPlayer ? GAME_KEYS.x : GAME_KEYS.o
      }`;
    }

    return status
  }
```

2022-02-15 19:57 UTC, LeoKuD commented on src/index.js
> +      isNavigationMode: false,
```
  resetGame() {
    this.setState((state) => {
      return {
        ...initialState(),
        nextPlayer: state.playerOne,
        isComputerMode: state.isComputerMode,
        isLevelHard: state.isLevelHard,
        isStart: state.isStart,
      };
    });
```

2022-02-15 20:06 UTC, LeoKuD commented on src/index.js
> +      isNavigationMode: false,
```
  resetGame() {
    this.setState((prevState) => {
      if (prevState.stepNumber) {
        return {
          ...initialState(),
          nextPlayer: prevState.playerOne,
          isComputerMode: prevState.isComputerMode,
          isLevelHard: prevState.isLevelHard,
          isStart: prevState.isStart,
        };
      }
    });
```

2022-02-18 09:11 UTC, LeoKuD commented on src/helpers.js
> +  return calculateRandomIndex(randomLine);
Fixed.
```suggestion
  function getRandomIndex(combinations, currentGameState) {
  let randomLine = calculateRandomIndex(combinations).filter(
    (item) => !currentGameState[item]
  );

  return calculateRandomIndex(randomLine);
}
```

2022-02-18 09:12 UTC, LeoKuD commented on src/helpers.js
> +    Math.floor(Math.random() * combinations.length)
```suggestion
    function getRandomIndex(combinations, currentGameState) {
  let randomLine = calculateRandomIndex(combinations).filter(
    (item) => !currentGameState[item]
  );

  return calculateRandomIndex(randomLine);
}
```

2022-02-18 09:13 UTC, LeoKuD commented on src/helpers.js
> +  return calculateRandomIndex(randomLine);
Yes, sorry. Fixed.

2022-02-18 09:59 UTC, LeoKuD commented on src/helpers.js
> +  });
```suggestion
  export function getIndexEasyLevel(currentGameState) {
  let emptySquares = currentGameState
    .map((item, index) => (item ? null : index))
    .filter((item) => item !== null);
  return calculateRandomIndex(emptySquares);
}
```

2022-02-18 10:05 UTC, LeoKuD commented on src/index.js
> +          return {
```suggestion
                  return {
            ...prevState,
```

2022-02-18 10:08 UTC, LeoKuD commented on src/index.js
> +        ? { isStart: !prevState.isStart }
```suggestion
              !prevState.isStart
        ? { ...prevState, isStart: !prevState.isStart }
        : {
            ...initialState(),
            nextPlayer: prevState.playerOne,
            isComputerMode: prevState.isComputerMode,
            isLevelHard: prevState.isLevelHard,
            isStart: !prevState.isStart,
          }
```

2022-02-18 10:17 UTC, LeoKuD commented on src/index.js
> +      current = state.history[state.stepNumber].squares;
Yes, this is wrong. Deleted this function.

2022-02-18 10:28 UTC, LeoKuD commented on src/index.js
> +      }
```suggestion
        resetGame() {
    this.setState((prevState) =>
      prevState.stepNumber
        ? {
            ...initialState(),
            nextPlayer: prevState.playerOne,
            isComputerMode: prevState.isComputerMode,
            isLevelHard: prevState.isLevelHard,
            isStart: prevState.isStart,
          }
        : {
            ...initialState(),
          }
    );
    this.score.roundCompleted = false;
  }
```

2022-02-18 10:38 UTC, LeoKuD commented on src/index.js
> +      return {
```suggestion
            return {
        ...prevState,
```

2022-02-18 10:41 UTC, LeoKuD commented on src/index.js
> +    let status = this.updateStatus();
Deleted extra variable.
```suggestion
     render() {
    return (
```

2022-02-19 09:57 UTC, maximsan approved these changes
Looks good and It's approved!  You need 1 more approve 🙂 Let me know when you will have 2 approves

2022-02-25 20:11 UTC, Dev1LtJ requested changes
Hello! I left some comments. Try to fix them and ping me once it's done.

2022-02-25 20:11 UTC, Dev1LtJ commented on src/helpers.js
> +export function getIndexHardLevel(currentGameState, stepNumber) {
What does this function do?

2022-02-25 20:11 UTC, Dev1LtJ commented on src/helpers.js
> +  }
You have a lot of repetitive code. Seems like you can simplify it. Try, please.

2022-02-25 20:11 UTC, Dev1LtJ commented on src/components/gameInfo/index.jsx
> +        changeLavelEasyHandleClick={changeLavelEasyHandleClick}
level?

2022-02-25 20:11 UTC, Dev1LtJ commented on src/index.js
> +    this.score.roundCompleted = false;
Why don't you save it in the Store?

2022-02-26 08:28 UTC, LeoKuD commented on src/components/gameInfo/index.jsx
> +        changeLavelEasyHandleClick={changeLavelEasyHandleClick}
```suggestion
          changeLevelHardHandleClick={this.changeLevelHardHandleClick}
          changeLevelEasyHandleClick={this.changeLevelEasyHandleClick}
```

2022-02-26 08:53 UTC, LeoKuD commented on src/index.js
> +    this.score.roundCompleted = false;
Ok, moved to State.

```suggestion
      return { ...prevState, roundCompleted: true };
```

2022-02-26 09:46 UTC, LeoKuD commented on src/helpers.js
> +  }
```suggestion
     for (let i = 0; i < LINES.length; i++) {
    const [a, b, c] = LINES[i];
    if (checkPlayerWinnerCombitation(GAME_KEYS.o, [a, b, c])) {
      playerWinnerСombinations.push(
        checkPlayerWinnerCombitation(GAME_KEYS.o, [a, b, c])
      );
    }
    if (checkPlayerWinnerCombitation(GAME_KEYS.x, [a, b, c])) {
      computerWinnerСombinations.push(
        checkPlayerWinnerCombitation(GAME_KEYS.x, [a, b, c])
      );
    }
    if (checkAvailableСombinations(GAME_KEYS.x, [a, b, c])) {
      availableСombinationsX.push(
        checkAvailableСombinations(GAME_KEYS.x, [a, b, c])
      );
    }
    if (checkAvailableСombinations(GAME_KEYS.o, [a, b, c])) {
      availableСombinationsO.push(
        checkAvailableСombinations(GAME_KEYS.o, [a, b, c])
      );
    }
  }
```

2022-03-03 17:35 UTC, oleg3555 approved these changes
Hello, good work!)

2022-03-10 13:42 UTC, merged